#!/bin/sh

set -eux
gem sources --remove https://rubygems.org/
gem sources -a https://mirrors.aliyun.com/rubygems/
bundle config set mirror.http://rubygems.org https://mirrors.aliyun.com/rubygems/
bundle config set deployment true
bundle config set global_gem_cache true
