# build stage
FROM node:20-alpine as builder

RUN set -eux; \
    sed -i "s@dl-cdn.alpinelinux.org@mirrors.aliyun.com@g" /etc/apk/repositories; \
    apk add --no-cache curl git g++ gcc make

COPY . /app

WORKDIR /app

RUN set -eux; \
    npm config set registry https://registry.npmmirror.com; \
    sed -i "s@standalone@export@g" next.config.mjs; \
    npm install; npm run build

# statc serve stage
FROM nginx:1.26-alpine
COPY --from=builder /app/out /usr/share/nginx/html
